Repository netlify/netlify-plugin-gatsby, pull requests merged in 2021-05, with the labels that each got.

#8 chore: format
  .gitignore
  src/index.js
  src/templates/createRequestObject.js
  src/templates/createResponseObject.js
  src/templates/gatsby.js
  src/templates/gatsbyFunction.js
Labels: chore

#9 chore: fix dependencies and imports
  package.json
  src/templates/createRequestObject.js
  src/templates/gatsby.js
  src/templates/gatsbyFunction.js
Labels: chore

#12 feat: support for node12, tracking gatsby node dep
  netlify.toml
  test/fixtures/functions-without-gatsby-plugin/.nvmrc
Labels: type: feature

#13 fix: handle gitignore line endings
  src/helpers/config.js
  src/index.js
  test/fixtures/functions-without-gatsby-plugin/.gitignore
  test/fixtures/functions-without-gatsby-plugin/_redirects
Labels: type: fix

#15 chore: add readme
  README.md
Labels: type: chore

#16 fix: allow functions to overwrite
  src/index.js
Labels: type: fix

#17 fix: remove logs in spliceconfig
  src/helpers/config.js
Labels: type: fix

#18 chore: renaming stuff before publish
  .github/ISSUE_TEMPLATE/bug_report.md
  package-lock.json
  package.json
  src/index.js
  test/fixtures/functions-without-gatsby-plugin/.gitignore
Labels: type: chore

#21 fix: try reordering the install script
  test/fixtures/functions-without-gatsby-plugin/package.json
Labels: type: fix

#22 chore: add labeler action
  .github/workflows/labeler.yml
Labels: type: chore

#20 feat: add support for file uploads in Gatsby
  src/templates/gatsbyFunction.js
  test/fixtures/functions-without-gatsby-plugin/e2e-tests/__snapshots__/functions.test.js.snap
  test/fixtures/functions-without-gatsby-plugin/e2e-tests/fixtures/test.txt
  test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
  test/fixtures/functions-without-gatsby-plugin/src/api/parser.js
  test/fixtures/functions-without-gatsby-plugin/src/pages/index.js
Labels: type: feature

#26 fix: don't break for sites without functions enabled
  src/index.js
Labels: type: bug

#29 test: add test for site without functions
  test/e2e-test.sh
  test/fixtures/functions-without-gatsby-plugin/.gitignore
  test/fixtures/functions-without-gatsby-plugin/package-lock.json
  test/fixtures/functions-without-gatsby-plugin/package.json
  test/fixtures/no-functions/.gitignore
  test/fixtures/no-functions/.netlify/state.json
  test/fixtures/no-functions/LICENSE
  test/fixtures/no-functions/README.md
  test/fixtures/no-functions/gatsby-config.js
  test/fixtures/no-functions/netlify.toml
  test/fixtures/no-functions/package.json
  test/fixtures/no-functions/src/images/icon.png
  test/fixtures/no-functions/src/pages/404.js
  test/fixtures/no-functions/src/pages/index.js
Labels: type: chore
