Repository netlify/netlify-plugin-gatsby, pull requests merged in 2021-06, with the labels that each got.

#56 Add readme logo
  README.md
  netlify-gatsby-plugin.png
Labels: type: chore

#59 fix: handle missing gatsby-config or plugins array
  plugin/src/index.js
  plugin/test/fixtures/with-no-gatsby-config/.gitignore
  plugin/test/fixtures/with-no-gatsby-config/.netlify/state.json
  plugin/test/fixtures/with-no-gatsby-config/LICENSE
  plugin/test/fixtures/with-no-gatsby-config/README.md
  plugin/test/fixtures/with-no-gatsby-config/e2e-tests/build.test.js
  plugin/test/fixtures/with-no-gatsby-config/netlify.toml
  plugin/test/fixtures/with-no-gatsby-config/package.json
  plugin/test/fixtures/with-no-gatsby-config/src/pages/404.js
  plugin/test/fixtures/with-no-gatsby-config/src/pages/index.js
  plugin/test/fixtures/with-no-plugins/.gitignore
  plugin/test/fixtures/with-no-plugins/.netlify/state.json
  plugin/test/fixtures/with-no-plugins/LICENSE
  plugin/test/fixtures/with-no-plugins/README.md
  plugin/test/fixtures/with-no-plugins/e2e-tests/build.test.js
  plugin/test/fixtures/with-no-plugins/gatsby-config.js
  plugin/test/fixtures/with-no-plugins/netlify.toml
  plugin/test/fixtures/with-no-plugins/package.json
  plugin/test/fixtures/with-no-plugins/src/pages/404.js
  plugin/test/fixtures/with-no-plugins/src/pages/index.js
Labels: type: bug

#60 feat: show build status summary
  plugin/src/index.js
Labels: type: feature

#63 feat: proxy functions during `ntl dev`
  plugin/package-lock.json
  plugin/package.json
  plugin/src/templates/functions.js
  plugin/src/templates/gatsby.js
  plugin/test/fixtures/custom-functions-directory/e2e-tests/__snapshots__/functions.test.js.snap
  plugin/test/fixtures/custom-functions-directory/e2e-tests/test-helpers.js
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/__snapshots__/functions.test.js.snap
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
Labels: type: feature

#65 docs: adds Gatsby Cache note to readme
  README.md
Labels: type: chore

#66 fix(plugin-package-json): add bugs url
  plugin/package.json
Labels: type: bug

#71 chore: fix `package-lock.json`
  package-lock.json
  plugin/package-lock.json
Labels: type: bug, type: chore

#72 chore: improve error handling
  plugin/src/index.js
Labels: type: chore

#73 chore: run ESLint/Prettier
  README.md
  plugin/src/index.js
Labels: type: chore
