Repository netlify/netlify-plugin-gatsby, pull requests merged in 2021-08, with the labels that each got.

#55 feat: use esbuild for functions
  .gitignore
  plugin/src/index.js
  plugin/src/templates/__gatsby-functions.ts
  plugin/src/templates/gatsbyFunction.js
Labels: type: feature

#98 bug: patch fossa install process
  .github/workflows/fossa.yml
Labels: type: chore

#92 fix: conditionally proxy dev functions
  .gitignore
  demo/.env.development
  demo/package.json
  plugin/src/index.js
  plugin/src/templates/__gatsby-functions.ts
  plugin/src/templates/createResponseObject.js
  plugin/src/templates/functions.js
  plugin/src/templates/gatsbyFunction.js
  plugin/test/fixtures/custom-functions-directory/e2e-tests/__snapshots__/functions.test.js.snap
  plugin/test/fixtures/custom-functions-directory/e2e-tests/test-helpers.js
  plugin/test/fixtures/custom-functions-directory/src/api/i-am-text.js
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/__snapshots__/functions.test.js.snap
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/functions.test.js
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
  plugin/test/fixtures/functions-without-gatsby-plugin/src/api/i-am-text.js
Labels: type: bug

#104 chore: add build step to support ts and esm
  .github/workflows/test.yml
  .gitignore
  demo/package.json
  plugin/.gitignore
  plugin/package-lock.json
  plugin/package.json
  plugin/src/index.js
Labels: type: chore
