Repository netlify/netlify-plugin-gatsby, pull requests merged in 2022-07, with the labels that each got.

#427 chore: add automation for issues to project
  .github/workflows/add-to-project.yml
Labels: type: chore, automerge

#431 fix: support scoped names for platform binary packages in lmdb
  plugin/src/helpers/files.ts
Labels: type: fix, type: bug, automerge

#430 test: fix unit tests
  demo/package-lock.json
  plugin/test/unit/helpers/config.spec.ts
  plugin/test/unit/templates/utils.spec.ts
Labels: type: chore

#435 feat: do not pre-warm lambdas if DEPLOY_PRIME_URL is not set
  plugin/src/helpers/config.ts
  plugin/src/index.ts
  plugin/test/helpers.js
  plugin/test/unit/helpers/config.spec.ts
  plugin/test/unit/index.spec.ts
  plugin/test/unit/templates/utils.spec.ts
Labels: type: feature, automerge

#441 fix: add fs.promises to linked filesystem
  plugin/src/templates/utils.ts
  plugin/test/unit/templates/utils.spec.ts
Labels: bug, type: bug, automerge

#440 feat: handle number and object responses correctly in functions
  demo/package-lock.json
  plugin/package-lock.json
  plugin/package.json
  plugin/src/templates/api/utils.ts
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
  plugin/test/fixtures/functions-without-gatsby-plugin/src/api/i-am-false.js
  plugin/test/fixtures/functions-without-gatsby-plugin/src/api/i-am-json-too.js
  plugin/test/fixtures/functions-without-gatsby-plugin/src/api/i-am-status.js
Labels: type: feature, automerge
