Repository netlify/netlify-plugin-gatsby, pull requests merged in 2022-03, with the labels that each got.

#303 feat: image cdn support
  .prettierignore
  README.md
  demo/netlify.toml
  demo/package.json
  plugin/package-lock.json
  plugin/package.json
  plugin/src/helpers/functions.ts
  plugin/src/index.ts
  plugin/src/templates/ipx.ts
  plugin/test/fixtures/functions-without-gatsby-plugin/package.json
  plugin/test/fixtures/no-functions/package.json
  plugin/test/fixtures/with-no-gatsby-config/package.json
  plugin/test/fixtures/with-no-plugins/package.json
  plugin/test/fixtures/with-old-gatsby-plugin/package.json
  plugin/test/fixtures/with-old-netlify-plugin/package.json
Labels: type: feature, automerge

#305 feat: add support for `/_gatsby/file/*` redirects
  plugin/src/helpers/functions.ts
  plugin/src/templates/ipx.ts
Labels: type: feature, automerge

#307 fix: update image CDN docs and defaults
  README.md
  docs/image-cdn.md
  plugin/src/helpers/functions.ts
  plugin/src/index.ts
Labels: type: bug, automerge

#322 fix: patch new lmdb binary location
  plugin/src/helpers/files.ts
Labels: type: bug, automerge

#327 fix: resolve lmdb binaries correctly
  plugin/src/helpers/files.ts
Labels: type: bug, automerge

#331 ci: remove pinned release please version
  release-please-config.json
Labels: type: chore, automerge
