Repository netlify/netlify-plugin-gatsby, pull requests merged in 2022-01, with the labels that each got.

#225 chore: Remove `AWS_JS_LAMBDA_RUNTIME` check
  README.md
  plugin/src/helpers/environment.ts
  plugin/src/index.ts
Labels: automerge

#224 chore: fix Husky
  package-lock.json
  package.json
Labels: type: chore, automerge

#231 chore: fix commitlint
  commitlint.config.js
Labels: type: chore, automerge

#232 fix: update path parsing to match Gatsby
  .github/workflows/test.yml
  plugin/package-lock.json
  plugin/package.json
  plugin/src/templates/api/gatsbyFunction.ts
  plugin/test/fixtures/custom-functions-directory/.env.development
  plugin/test/fixtures/custom-functions-directory/.env.production
  plugin/test/fixtures/custom-functions-directory/.gitignore
  plugin/test/fixtures/custom-functions-directory/.nvmrc
  plugin/test/fixtures/custom-functions-directory/README.md
  plugin/test/fixtures/custom-functions-directory/e2e-tests/__snapshots__/functions.test.js.snap
  plugin/test/fixtures/custom-functions-directory/e2e-tests/fixtures/test.txt
  plugin/test/fixtures/custom-functions-directory/e2e-tests/functions.test.js
  plugin/test/fixtures/custom-functions-directory/e2e-tests/test-helpers.js
  plugin/test/fixtures/custom-functions-directory/gatsby-config.js
  plugin/test/fixtures/custom-functions-directory/netlify.toml
  plugin/test/fixtures/custom-functions-directory/package.json
  plugin/test/fixtures/custom-functions-directory/src/api/I-Am-Capitalized.js
  plugin/test/fixtures/custom-functions-directory/src/api/a-directory/function.js
  plugin/test/fixtures/custom-functions-directory/src/api/a-directory/index.js
  plugin/test/fixtures/custom-functions-directory/src/api/cookie-me.ts
  plugin/test/fixtures/custom-functions-directory/src/api/cors.js
  plugin/test/fixtures/custom-functions-directory/src/api/dir/[...].js
  plugin/test/fixtures/custom-functions-directory/src/api/dir/function.js
  plugin/test/fixtures/custom-functions-directory/src/api/env-variables.js
  plugin/test/fixtures/custom-functions-directory/src/api/error-send-function-twice.js
  plugin/test/fixtures/custom-functions-directory/src/api/hello-ts.ts
  plugin/test/fixtures/custom-functions-directory/src/api/hello-world.js
  plugin/test/fixtures/custom-functions-directory/src/api/i-am-json.js
  plugin/test/fixtures/custom-functions-directory/src/api/i-am-text.js
  plugin/test/fixtures/custom-functions-directory/src/api/i-am-typescript.ts
  plugin/test/fixtures/custom-functions-directory/src/api/parser.js
  plugin/test/fixtures/custom-functions-directory/src/api/redirect-me.ts
  plugin/test/fixtures/custom-functions-directory/src/api/some whitespace.js
  plugin/test/fixtures/custom-functions-directory/src/api/some-àè-french.js
  plugin/test/fixtures/custom-functions-directory/src/api/some-אודות.js
  plugin/test/fixtures/custom-functions-directory/src/api/status.js
  plugin/test/fixtures/custom-functions-directory/src/api/top-level.js
  plugin/test/fixtures/custom-functions-directory/src/api/users/[userId]/[super].js
  plugin/test/fixtures/custom-functions-directory/src/api/with-äöü-umlaut.js
  plugin/test/fixtures/custom-functions-directory/src/images/icon.png
  plugin/test/fixtures/custom-functions-directory/src/pages/404.js
  plugin/test/fixtures/custom-functions-directory/src/pages/index.js
  plugin/test/fixtures/functions-without-gatsby-plugin/.env.development
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/__snapshots__/functions.test.js.snap
  plugin/test/fixtures/functions-without-gatsby-plugin/package.json
  plugin/test/fixtures/no-functions/e2e-tests/build.test.js
  plugin/test/fixtures/with-no-gatsby-config/e2e-tests/build.test.js
  plugin/test/fixtures/with-no-plugins/e2e-tests/build.test.js
  plugin/test/fixtures/with-old-gatsby-plugin/e2e-tests/build.test.js
  plugin/test/fixtures/with-old-netlify-plugin/e2e-tests/build.test.js
Labels: type: bug, automerge

#235 fix: generate handlers with correct site root
  .eslintrc.js
  plugin/package-lock.json
  plugin/package.json
  plugin/src/helpers/config.ts
  plugin/src/helpers/functions.ts
  plugin/src/index.ts
  plugin/src/templates/api/gatsbyFunction.ts
  plugin/src/templates/api/utils.ts
  plugin/src/templates/dsg/__dsg.ts
  plugin/src/templates/handlers.ts
  plugin/src/templates/ssr/__ssr.ts
  plugin/src/templates/ssr/utils.ts
  plugin/src/templates/utils.ts
Labels: type: bug, automerge

#200 chore: add release-please
  .github/workflows/pre-release.yml
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#243 chore: temporarily disable `build.ignore`
  demo/netlify.toml
Labels: type: chore, automerge

#244 feat: add support for custom error pages
  demo/src/pages/500.js
  demo/src/pages/bad-dog.js
  demo/src/pages/index.js
  plugin/src/helpers/config.ts
  plugin/src/templates/handlers.ts
  plugin/src/templates/utils.ts
  plugin/test/fixtures/functions-without-gatsby-plugin/e2e-tests/test-helpers.js
Labels: type: feature, automerge

#241 feat: handle large zipfiles
  plugin/package-lock.json
  plugin/package.json
  plugin/src/helpers/config.ts
  plugin/src/helpers/verification.ts
  plugin/src/index.ts
Labels: type: feature, automerge

#240 feat: support disabling of Netlify function generation
  README.md
  plugin/src/helpers/config.ts
  plugin/src/helpers/functions.ts
  plugin/src/index.ts
  plugin/src/templates/handlers.ts
  plugin/test/fixtures/with-no-gatsby-config/e2e-tests/build.test.js
  plugin/test/fixtures/with-no-plugins/e2e-tests/build.test.js
Labels: type: feature, automerge

#239 chore: update readme for GA
  README.md
Labels: type: chore, automerge

#249 fix: correct publish file
  plugin/package.json
Labels: type: bug, automerge

#250 chore: release plugin path
  .github/workflows/release-please.yml
Labels: type: chore, automerge
