Repository netlify/netlify-plugin-gatsby, pull requests merged in 2022-04, with the labels that each got.

#334 fix!: remove catch-all DSG redirect and handle discretely
  README.md
  plugin/package-lock.json
  plugin/package.json
  plugin/src/helpers/config.ts
  plugin/src/helpers/files.ts
  plugin/src/index.ts
Labels: type: bug, automerge

#343 ci(github-actions): :zap: add caching of dependencies to improve test build times
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: type: chore, automerge

#350 ci: :sparkles: run tests on a nightly basis
  .github/workflows/test.yml
Labels: type: chore, automerge

#352 chore: switch to more detailed yml based bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type: chore
