Repository netlify/netlify-plugin-gatsby, pull requests merged in 2022-02, with the labels that each got.

#252 chore: v2.0.1
  plugin/package-lock.json
  plugin/package.json
Labels: type: chore, automerge

#256 ci(release-please): switch to manifest release
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: type: chore, automerge

#253 fix: ensure lmdb correct binaries are available for lambdas
  .nvmrc
  demo/.nvmrc
  demo/netlify.toml
  demo/package-lock.json
  demo/package.json
  plugin/src/helpers/files.ts
  plugin/src/index.ts
Labels: type: bug, automerge

#281 fix: support gatsby base dirs outside the site root
  plugin/src/helpers/cache.ts
  plugin/src/helpers/config.ts
  plugin/src/helpers/functions.ts
  plugin/src/index.ts
  plugin/src/templates/api/__api.ts
  plugin/src/templates/api/gatsbyFunction.ts
  plugin/src/templates/handlers.ts
Labels: type: bug, automerge

#283 ci: auto-submit released plugins
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#286 ci: release-please bootstrap
  .release-please-manifest.json
  release-please-config.json
Labels: type: chore, automerge

#288 chore(main): release plugin-gatsby 2.0.3
  .release-please-manifest.json
  plugin/CHANGELOG.md
  plugin/package-lock.json
  plugin/package.json
Labels: type: chore, automerge, autorelease: pending

#292 fix: remove confusing error log
  package-lock.json
  plugin/src/helpers/files.ts
Labels: type: bug, automerge

#293 chore(main): release plugin-gatsby 2.0.4
  .prettierignore
  .release-please-manifest.json
  plugin/CHANGELOG.md
  plugin/package-lock.json
  plugin/package.json
Labels: type: chore, automerge, autorelease: pending
